### ISSUE TITLE
Shop menu won't close with Use key under certain circumstances

### ISSUE THREAD

**Issue by wildweasel486** [wildweasel486/ww-cash2#2]
Firstly, awesome work on the shop system, Ed. I really appreciate the work you've put in here.

The issue I've found, though, is if you've opened the shop menu and are still skating past it. (Best one to test is the chainsaw on Doom 2 Map01.) Use the vending machine while strafing to the left, so that your crosshair drifts past the machine as the shop menu opens. The Use key will no longer be able to close the window. (The +zoom button can be used as a last resort, but this may confuse some players!)

**Comment by edthebat** [comment]
I'm glad you like what I've done. As you can see, though, it still needs some work...

I think I already know what the root of the problem is. I'll come up with a fix for it soon. As well as better comments on my scripts; some things could use some better explanation, still.

**Comment by edthebat** [comment]
Fix was easy. Pushing now.

**Comment by wildweasel486** [comment]
Excellent, thank you.
