### ISSUE TITLE
Shop "intro" descriptions are missing?

### ISSUE THREAD

**Issue by wildweasel486** [wildweasel486/ww-cash2#4]
I see some commented-out lines apparently intended to display the shop's intro text (SHOP*_MAIN in Language), but I've got no idea how to enable this functionality myself.

**Comment by edthebat** [comment]
I can put those in someplace. I just didn't quite get to deciding where the best place would be. Perhaps it can go in the large 'item description' box when the player first activates the machine, up until they highlight a selection?

**Comment by edthebat** [comment]
Descriptions will need linebreak formatting, but otherwise this step should be done.
