### ISSUE TITLE
PWYB: "ACS: I don't know what  is."

### ISSUE THREAD

**Issue by wildweasel486** [wildweasel486/ww-cash2#5]
I suspect Pay With Your Blood (now the "BLEED:" button...hmm, maybe I should make a new icon for that =P) doesn't quite work. In attempting to purchase the Hurricane Fist with hit points, it takes the HP (I fixed a typo on the damagetype, BTW, so it doesn't take armor) but doesn't give the upgrade.

**Comment by edthebat** [comment]
Whoops, had the wrong index number on a call in the shop. Sending a fix up now. And my bad on the typo; must have been tired when I typed that in.
