### ISSUE TITLE
Can't use the terminals at all now

### ISSUE THREAD

**Issue by wildweasel486** [wildweasel486/ww-cash2#9]
I suspect it's been a while since I last actually tried to play my own mod, but I can no longer activate the vending machines. I suspect [this commit](https://github.com/wildweasel486/ww-cash2/commit/2a9f2cdd36fd32c265cf4f9ad658c9da023da9cb) is where the problem stems from; the script has been changed to check for the Zoom key, but this no longer actually does anything, and the vending machines themselves are still set to respond to the Use key and executing the numbered script 9001 which no longer exists.

I have no idea where to begin, here.

**Comment by edthebat** [comment]
Since this was related to my work, I took it upon myself to fix it. Somehow, some of the changes either got lost or never got put into the repo in the first place. I've committed the missing bits.

**Comment by wildweasel486** [comment]
Thanks for your quick help, it all works again (through my quick test run of map31/32).
